# Generated by Django 4.2.1 on 2023-09-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pessoa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="sobrenome",
            field=models.CharField(max_length=150, verbose_name="Sobrenome"),
        ),
    ]
