# Generated by Django 4.2.1 on 2023-09-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pessoa", "0002_alter_cliente_sobrenome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="sobrenome",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Sobrenome"
            ),
        ),
    ]
