version: '3'

services:
  db:
    image: postgres:latest
    ports:
      - "5433:5433"

  web:
    build: ./
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: barberease
    volumes:
      - .:/barberease
    ports:
      - "8000:8000"
    depends_on:
      - db
